solution
mate-academy/react_person pull request #1008
Opened 2023-01-26 19:09 UTC by Vadivel-Babu

2023-01-27 09:09 UTC, polosanya requested changes
Please don't forget to add a link to your PR description
![image](https://user-images.githubusercontent.com/96409563/215049271-1a435f5f-6031-4f22-9214-801cff7123f6.png)

2023-01-27 09:09 UTC, polosanya commented on src/components/Person/Person.jsx
> +      <p className="Person__partner">{married}</p>
```suggestion
      <h2 className="Person__name">{name}</h2>
      
      {person.age 
        && <p className="Person__age">{`I am ${person.age}`}</p>}
      
      <p className="Person__partner">{married}</p>
```

2023-01-27 09:09 UTC, polosanya commented on src/components/Person/Person.jsx
> +export const Person = ({ person }) => {
![image](https://user-images.githubusercontent.com/96409563/215049026-ddf8d478-5c70-426a-a429-91b7a3adeceb.png)

2023-01-27 09:09 UTC, polosanya commented on src/components/Person/Person.jsx
> +  const name = `My name is ${person.name}`;
I'm not sure if you need this variable. You can add this string directly

2023-01-27 16:28 UTC, Volodymyr-Melnyk-Fron10der requested changes
Hi! Seems like you didn't fix all previous comments, check them again please

2023-01-27 16:28 UTC, Volodymyr-Melnyk-Fron10der commented on src/components/Person/Person.jsx
> +      <p className="Person__partner">{married}</p>
Add divided empty lines as it was said in previous mentor's comment

2023-02-01 20:12 UTC, polosanya requested changes
Let's polish it up) 
Don't forget to push the changes
Feel free to ask for help in the Slack chat if you have any difficulties)

2023-02-01 20:12 UTC, polosanya commented on src/components/Person/Person.jsx
> +  const { name, sex, age, isMarried, partnerName } = person;
```suggestion
  const { 
    name, 
    sex, 
    age, 
    isMarried, 
    partnerName,
  } = person;
```

2023-02-01 20:12 UTC, polosanya commented on src/components/Person/Person.jsx
> +      <p className="Person__partner">
```suggestion
      <h2 className="Person__name">{`My name is ${name}`}</h2>
      
      {age && <p className="Person__age">{`I am ${age}`}</p>}
      
      <p className="Person__partner">
```

2023-02-01 20:12 UTC, polosanya commented on src/components/Person/Person.jsx
> +        {isMarried ? `${partnerName} is my ${Sex}` : 'I am not married'}
```suggestion
        {isMarried 
          ? `${partnerName} is my ${Sex}` 
          : 'I am not married'}
```

2023-02-16 12:57 UTC, Vadivel-Babu commented
I formatted the document as per you said but if I save the document after change the format it went back to single line.

2023-02-16 14:19 UTC, Volodymyr-Melnyk-Fron10der approved these changes
Good then👍

2024-12-06 08:28 UTC, closed without merging