Solution
mate-academy/react_person pull request #1114
Opened 2023-03-12 22:05 UTC by MaksymMaliuk

[DEMO LINK](https://MaksymMaliuk.github.io/react_person/)

2023-03-13 16:00 UTC, Vlados3611 approved these changes
Good work 👍

2023-03-14 14:50 UTC, Andr1yK requested changes

2023-03-14 14:50 UTC, Andr1yK commented on src/components/Person/Person.jsx
> +}
avoid nested IFs, it's hard to reed :(

2023-03-14 14:50 UTC, Andr1yK commented on src/components/Person/Person.jsx
> +}
let's refactor it)

2023-03-14 14:50 UTC, Andr1yK commented on src/components/Person/Person.jsx
> +      )}
fix indents

2023-03-14 14:50 UTC, Andr1yK commented on src/components/Person/Person.jsx
> +      )}
if age = 0 I will see 0 :)

2023-03-14 15:37 UTC, Andr1yK approved these changes

2024-04-21 22:51 UTC, closed without merging