Develop
mate-academy/react_person pull request #123
Opened 2021-11-03 12:49 UTC by cyb1ove

[DEMO LINK](https://cyb1ove.github.io/react_person/)

2021-11-03 13:44 UTC, MariiaObraztsova approved these changes

2021-11-04 07:15 UTC, VinnieJ-2k20 requested changes
Couple of fixes left.

2021-11-04 07:15 UTC, VinnieJ-2k20 commented on src/Person/Person.jsx
> +      }
This logic is too complex for JSX.
Move it to a variable.

2021-11-04 07:15 UTC, VinnieJ-2k20 commented on src/Person/Person.jsx
> +  partnerName: PropTypes.string.isRequired,
Not all prop attributes are required.

2021-11-04 07:36 UTC, VinnieJ-2k20 requested changes
Final fix.

2021-11-04 07:36 UTC, VinnieJ-2k20 commented on src/Person/Person.jsx
> +        {isMarried && marriedSentence}
Use ternary here.
```suggestion
        {isMarried
          ? marriedSentence
          : 'I am not married'}
```

2021-11-04 07:44 UTC, VinnieJ-2k20 approved these changes
Good job 👍

2025-01-20 16:33 UTC, closed without merging