Add React Person
mate-academy/react_person pull request #1281
Opened 2023-05-21 17:11 UTC by ruslanpashkov

[DEMO LINK](https://ruslanpashkov.github.io/react_person/)

2023-05-21 17:39 UTC, DidenkoDenis306 approved these changes

2023-05-22 07:34 UTC, silchyn requested changes
Read checklist carefully!

2023-05-22 07:34 UTC, silchyn commented on src/components/Person/Person.jsx
> +  const partner = sex === 'm'
```suggestion
  } = person;
  
  const partner = sex === 'm'
```

2023-05-22 07:34 UTC, silchyn commented on src/components/Person/Person.jsx
> +        )}
```suggestion
        {isMarried
          ? (
            `${partnerName} is my ${partner}`
          ) : (
            'I am not married'
          )}
```

2023-05-23 14:50 UTC, dinaminahi approved these changes
Well done 🥇

2023-12-12 12:56 UTC, closed without merging