solution
mate-academy/react_person pull request #1380
Opened 2023-06-26 14:59 UTC by MaxSchmide

- [DEMO LINK](https://maxschmide.github.io/react_person/)

2023-06-27 20:08 UTC, ManoylovAC requested changes
Good start
And you can better - please check my comments I left for you

2023-06-27 20:08 UTC, ManoylovAC commented on src/components/Person/Person.jsx
> +          ? `${partnerName} is my ${sex === 'f' ? 'husband' : 'wife'}`
Please not use ternary operator inside another one

for better readability you can create separate variable in component like `partnerStatus` and use it in jsx
```suggestion
  const partnerStatus = sex === 'm'
     ? 'wife'
     : 'husband';
     ...
     `${partnerName} is my ${partnerStatus}`
```

2023-06-27 20:08 UTC, ManoylovAC commented on src/components/Person/Person.jsx
> +
you can create styles file for `Person` component

2023-06-28 08:10 UTC, tetiana-ivanchenko approved these changes

2023-10-20 18:12 UTC, closed without merging