Develop
mate-academy/react_person pull request #1554
Opened 2023-08-11 14:16 UTC by YuriyBilskiy

[DEMO LINK](https://yuriybilskiy.github.io/react_person/

2023-08-11 18:01 UTC, TarasHoliuk requested changes

2023-08-11 18:01 UTC, TarasHoliuk commented on src/components/Person/Person.jsx
> +      ${sex === 'm' ? 'wife' : 'husband'}`}`}
that's a bit difficult to read
you may move `${partner} is my ${sex === 'm' ? 'wife' : 'husband'}`}` to a variable above and use here

2023-08-11 18:01 UTC, TarasHoliuk commented on src/App.jsx
> +      sex={misha.sex}
do not pass separate properties
you should pass an entire person object as a prop

2023-08-14 10:57 UTC, Anastasiia-Svintsova requested changes
Keep up the good job! Check my comments

2023-08-14 18:42 UTC, loralevitska approved these changes
Good job!

2024-08-07 15:35 UTC, closed without merging