Develop
mate-academy/react_person pull request #1583
Opened 2023-08-21 13:39 UTC by Valentyn-Bilyk

[DEMO LINK](https://Valentyn-Bilyk.github.io/react_person/)

2023-08-22 17:52 UTC, Anna-Tkachenko requested changes

2023-08-22 17:52 UTC, Anna-Tkachenko commented on src/components/Person/Person.jsx
> +      {`My name is ${person.name}`}
Let's use destructuring before the return statement

2023-08-22 17:52 UTC, Anna-Tkachenko commented on src/components/Person/Person.jsx
> +      )}
This code is not clear
It's hard to understand the result of this code
Will be better to create separate variable before the return statement for storing string with `wife` or `husband` value
Then use this variable inside the jsx

2023-08-23 07:36 UTC, Moroz-Dmytro requested changes

2023-08-23 07:36 UTC, Moroz-Dmytro commented on src/components/Person/Person.jsx
> +      }
```suggestion
      {Boolean(age) && (
        <p className="Person__age">
          {`I am ${age}`}
        </p>
      )}
```

2023-08-23 07:36 UTC, Moroz-Dmytro commented on src/components/Person/Person.jsx
> +        }
```suggestion
        {isMarried
          ? `${partnerName} is my ${partnerDesignation}`
          : 'I am not married'
        }
```

2023-08-23 08:30 UTC, roman-mirzoian approved these changes
Well done 👍

2023-08-23 08:30 UTC, roman-mirzoian commented on src/components/Person/Person.jsx
> +  const partnerDesignation = sex === 'm'
It would be cool to put the "magic values" in constants:
```js
const MALE = 'm';
...
const parterDesignation = sex === MALE ...
```

2026-01-24 21:50 UTC, closed without merging