Task done
mate-academy/react_person pull request #191
Opened 2021-12-22 01:20 UTC by Virass

[DEMO LINK](https://Virass.github.io/react_person/)

- Use conditional rendering
- Move styles to correct file

2021-12-22 12:32 UTC, varseniuk requested changes

2021-12-22 12:32 UTC, varseniuk commented on src/components/Person.jsx
> +        </p>
```suggestion
        {age && (
          <p className="Person__age">
            `I am ${age}`
          </p>
        )
```
Зараз ти рендерший пустий тег p, якщо немає age. Давай взагалі його рендерити тільки тоді, коли age є

2022-02-22 10:11 UTC, vitaliy-martynyuk approved these changes
well done! 🚀

2022-02-22 10:11 UTC, vitaliy-martynyuk commented on src/components/Person.jsx
> +        {age > 0 && (
```suggestion
        {age && (
```

2022-03-09 11:33 UTC, vitaliy-martynyuk approved these changes

2026-03-02 19:46 UTC, closed without merging