Add solution
mate-academy/react_person pull request #1977
Opened 2024-01-02 14:48 UTC by ssaviak

[DEMO LINK](https://ssaviak.github.io/react_person/)

2024-01-02 15:21 UTC, olya-shyian requested changes
Superb! Nice work!🚀

2024-01-02 15:21 UTC, olya-shyian commented on src/components/Person/Person.jsx
> +      }
you can write simplier like 
```
{age && (
  <p className="Person__age">
    {`I am ${age}`}
  </p>
)}
      ```

2024-01-02 15:21 UTC, olya-shyian commented on src/components/Person/Person.jsx
> +          isMarried
you can leave `isMarried` in the same line with `{` bracket like

```
 {isMarried
    ?
```

2024-01-02 15:21 UTC, olya-shyian commented on src/components/Person/Person.jsx
> +  const isMan = sex === 'm';
you can improve this check , istead of `isMan` just find which one should be
``` const partner = sex === 'm' ? 'wife' : 'husband';```

2024-01-02 15:21 UTC, olya-shyian commented on src/components/Person/Person.jsx
> +  const { name, age, sex, isMarried, partnerName } = person;
I'm glad that you use destructuring here) well done)

2024-01-03 11:42 UTC, YegorKorenkov approved these changes
Gooood job!

2024-05-13 11:30 UTC, closed without merging