solved task
mate-academy/react_person pull request #2013
Opened 2024-01-13 14:26 UTC by hulchak

https://hulchak.github.io/react_person/

2024-01-13 14:45 UTC, VitaliyBondarenko1982 requested changes
Good job.
Please check comments.

2024-01-13 14:45 UTC, VitaliyBondarenko1982 commented on src/components/Person/Person.jsx
> +export const Person = ({ person }) => (
suggest destructure person

2024-01-13 14:45 UTC, VitaliyBondarenko1982 commented on src/components/Person/Person.jsx
> +    )}
we just need to decide which text will be rendered inside Person__partner element.
and better to make two separate ternary expressions in component for make code more readable.
```
const partner = person.sex === 'm' ? 'wife' : 'husband';
const personPartner = person.isMarried 
  ? `${person.partnerName} is my ${partner}`
  :  'I am not married';
```

```suggestion
      <p className="Person__partner">
        {personPartner}
      </p>
```

2024-01-15 15:10 UTC, nazarmatsevych approved these changes
🔥

2024-07-31 09:05 UTC, closed without merging