Develop
mate-academy/react_person pull request #203
Opened 2022-01-12 23:34 UTC by andrii-koptiev

https://andrii-koptiev.github.io/react_person/

2022-01-13 07:15 UTC, levix2l approved these changes

2022-01-13 07:15 UTC, levix2l commented on src/Person.jsx
> +  partnerName }) => (
}) => (
перенеси на некст строку

2022-01-13 07:15 UTC, levix2l commented on src/Person.jsx
> +  (
вместо этих скобок мы разве не используем <></>

2022-01-13 08:35 UTC, andrii-koptiev commented on src/Person.jsx
> +  (
Ты прав, но тут мы можем не использовать вообще никакие скобки, так как все теги находятся в одном блоке <section>

2022-01-17 14:21 UTC, Elena-brv requested changes

2022-01-17 14:21 UTC, Elena-brv commented on src/Person.jsx
> +export const Person = ({ name, age, sex, isMarried, partnerName }) => (
```suggestion
export const Person = ({ 
  name, 
  age, 
  sex, 
  isMarried, 
  partnerName 
}) => (
```

2022-01-17 14:21 UTC, Elena-brv commented on src/Person.jsx
> +    {age && <p className="Person__age">{`I am ${age}`}</p>}
```suggestion
    {age && (
      <p className="Person__age">
        {`I am ${age}`}
      </p>
    )}
```

2022-01-17 14:21 UTC, Elena-brv commented on src/Person.jsx
> +    )}
DRY, much code is repeated, optimize it

2022-01-17 15:42 UTC, Elena-brv approved these changes

2023-09-26 21:11 UTC, closed without merging