Develop
mate-academy/react_person pull request #2112
Opened 2024-02-23 20:52 UTC by BoGoBooM

[DEMO LINK](https://bogoboom.github.io/react_person/)

2024-02-24 07:59 UTC, Andriy-Shymkiv approved these changes
lgtm 👍🏻

2024-02-24 08:00 UTC, Andriy-Shymkiv requested changes

2024-02-24 08:00 UTC, Andriy-Shymkiv commented on src/components/Person/Person.jsx
> +        <p className="Person__age">I am {`I am ${person.age}`}</p>
```suggestion
        <p className="Person__age">{`I am ${person.age}`}</p>
```

2024-02-24 18:30 UTC, BoGoBooM commented
what does igtm mean?

2024-02-25 08:04 UTC, etojeDenys approved these changes
awesome

2025-02-17 11:53 UTC, closed without merging