create component
mate-academy/react_person pull request #2385
Opened 2024-05-24 18:22 UTC by Natallia3105

https://Natallia3105.github.io/react_person/

2024-05-24 18:31 UTC, vadiimvooo requested changes
Good job. There are a few things to fix.

2024-05-24 19:25 UTC, nazarmatsevych requested changes
Almost done, please fix the comments below

2024-05-25 05:32 UTC, volodymyr-soltys97 requested changes
Almost done!
Let's make your code better

2024-05-25 05:32 UTC, volodymyr-soltys97 commented on src/App.jsx
> +    </section> */}
Remove comments 
<img width="814" alt="image" src="https://github.com/mate-academy/react_person/assets/64750958/248cf66f-45a9-4331-8d8d-d641a3f5e4e7">

2024-05-25 05:32 UTC, volodymyr-soltys97 commented on src/components/Person/Person.jsx
> +      </p>
```suggestion
      <h2 className="Person__name">{`My name is ${name}`}</h2>
      
      {age && <p className="Person__age">{`I am ${age}`}</p>}
      
      <p className="Person__partner">
        {isMarried
          ? `${partnerName} is my ${partner}`
          : 'I am not married'}
      </p>
```

2024-05-25 12:03 UTC, nazarmatsevych approved these changes
Awesome 🔥

2025-01-24 13:23 UTC, closed without merging