task complete
mate-academy/react_person pull request #243
Opened 2022-01-22 16:14 UTC by voronvasia

https://voronvasia.github.io/react_person/

2022-01-24 15:33 UTC, aliceblunt8 requested changes

2022-01-24 15:33 UTC, aliceblunt8 commented on src/components/Person.jsx
> +    </h2>
```suggestion
    {name && (
      <h2 className="Person__name">
        {My name is ${name}`}
      </h2>
    )}
```

2022-01-24 15:33 UTC, aliceblunt8 commented on src/components/Person.jsx
> +      {age && `I am ${age}`}
same

2022-01-25 13:38 UTC, danylo-onishchuk approved these changes

2022-01-25 13:38 UTC, danylo-onishchuk commented on src/components/Person.scss
> +}
EOF

2023-12-09 19:53 UTC, closed without merging