solution
mate-academy/react_person pull request #2484
Opened 2024-07-24 19:44 UTC by MaxBorovique

[DEMO LINK](https://MaxBorovique.github.io/react_person/)

2024-07-24 21:52 UTC, DanilWeda requested changes
Good. 
Please check the comments that I left. 
Many thanks)

2024-07-24 21:52 UTC, DanilWeda commented on src/components/Person/Person.spec.jsx
You don`t need to change spec.jsx file. 
Please replace this file with initial markup

2024-07-24 21:52 UTC, DanilWeda commented on src/components/Person/Person.jsx
> +    if (partner.gender === 'female') {
```suggestion
    if (partner.gender === 'f') {
```
Check what gender value you have. 
Now all person not married! ( check demo link)

2024-07-24 21:52 UTC, DanilWeda commented on src/components/Person/Person.jsx
> +  let partnerInfo;
Try not to use let. You can find another variant for render this text ( try it)

2024-07-25 13:49 UTC, BudnikOleksii approved these changes
Good job 👍 
Approved, but left a comment, check it

2024-07-25 13:49 UTC, BudnikOleksii commented on src/components/Person/Person.jsx
> +        <p className="Person__partner">
`<p className="Person__partner">` you have the same in both cases, just a content is different

2025-02-08 22:39 UTC, closed without merging