task solved
mate-academy/react_person pull request #2572
Opened 2024-09-16 17:00 UTC by coldmelnyk

[DEMO LINK](https://coldmelnyk.github.io/react_person/)

2024-09-16 20:08 UTC, Moroz-Dmytro requested changes
Let's improve your solution 😉

2024-09-16 20:08 UTC, Moroz-Dmytro commented on src/components/Person/Person.jsx
> +      </p>
Use destructuring

2024-09-16 20:08 UTC, Moroz-Dmytro commented on src/components/Person/Person.jsx
> +  const ageMessage = `I am ${person.age}`;
You don't need to create consants for text

2024-09-16 20:08 UTC, Moroz-Dmytro commented on src/components/Person/Person.jsx
> +      </p>
```suggestion
      {person.age && <p className='Person__age' >
        {person.age}
      </p>
```

2024-09-17 06:33 UTC, BudnikOleksii approved these changes
Good job 👍

2025-07-18 21:51 UTC, closed without merging