Solution
mate-academy/react_person pull request #357
Opened 2022-04-30 16:09 UTC by plankton9991

[DEMO LINK](https://plankton9991.github.io/react_person/)

2022-04-30 18:07 UTC, misha200119 commented on src/App.js
> +    />
better set dataObject as 1 prop and destructure it in Person component

2022-04-30 18:07 UTC, misha200119 commented on src/App.js
> +    />
same

2022-04-30 18:07 UTC, misha200119 approved these changes

2022-05-03 09:45 UTC, MaksimusCRS requested changes

2022-05-03 09:45 UTC, MaksimusCRS commented on src/App.js
> +      partnerName={misha.partnerName}
```suggestion
      person={misha}
```

2022-05-03 09:45 UTC, MaksimusCRS commented on src/App.js
> +      partnerName={olya.partnerName}
same

2022-05-03 09:45 UTC, MaksimusCRS commented on src/App.js
> +      partnerName={alex.partnerName}
same

2022-05-03 09:45 UTC, MaksimusCRS commented on src/components/Person/Person.jsx
> +      <p className="Person__age">{`I am ${age}`}</p>
```suggestion
      <p className="Person__age">
        {`I am ${age}`}
      </p>
```

2022-05-03 09:45 UTC, MaksimusCRS commented on src/components/Person/Person.jsx
> +          : "husband'"}s name is ${partnerName}`}
You need variable for sex === 'm'
          ? "wife'"
          : "husband

2022-05-03 15:37 UTC, MaksimusCRS approved these changes

2022-05-03 15:37 UTC, MaksimusCRS commented on src/components/Person/Person.jsx
> +        <p className="Person__partner">I am not married</p>
you just change text here

2023-03-10 13:31 UTC, closed without merging