my solution
mate-academy/react_person pull request #449
Opened 2022-07-01 16:23 UTC by Pavlo000

2022-07-05 21:09 UTC, AKomashchuk approved these changes
Гарна робота!

2022-07-06 11:08 UTC, illiarerun requested changes

2022-07-06 11:08 UTC, illiarerun commented on src/App.js
> +    {Person(alex)}
Let's use `JSX` syntax, like `<Component propName={propValue} />

2022-07-06 11:08 UTC, illiarerun commented on src/components/Person/Person.jsx
> +      <p>{isMarried ? `My ${partnerSex()} ${partnerName}` : 'I am not married'}</p>
Let's not write code in one line, format it properly, also you forgot to add styles in `Person.scss`
```suggestion
      <p>
        {isMarried 
          ? `My ${partnerSex()} ${partnerName}` 
          : 'I am not married'
        }
      </p>
```

2022-07-06 11:08 UTC, illiarerun commented on src/components/Person/Person.jsx
> +        {` ${name}`}
use interpolation

2022-07-06 11:08 UTC, illiarerun commented on src/components/Person/Person.jsx
> +          {` ${age}`}
here also

2022-07-06 11:26 UTC, jstmpelowycz approved these changes

2024-11-26 18:32 UTC, closed without merging