lets see
mate-academy/react_person pull request #483
Opened 2022-07-04 15:31 UTC by Havrysh

2022-07-05 19:46 UTC, marina-tilniak requested changes
додай Person.jsx

2022-07-05 19:46 UTC, marina-tilniak commented on src/App.js
> +      />
```suggestion
      <Person {...misha} />
```

2022-07-05 19:46 UTC, marina-tilniak commented on src/App.js
> +      />
так як ці змінні тобі тут не потрібні можна передавати об'єкт і робити деструктуризацію в компоненті Person

2022-07-07 21:01 UTC, marina-tilniak requested changes

2022-07-07 21:01 UTC, marina-tilniak commented on src/components/Person.jsx
> +      </p>
same here

2022-07-08 08:58 UTC, Havrysh commented on src/components/Person.jsx
> +    ): null}
Got you, wrote this way bcs saw it in Mykhailo's video

2022-07-09 18:44 UTC, marina-tilniak commented on src/components/Person.jsx
> +    ): null}
I think it's more readable option and we use it in our projects, but in your future company you could find your option and it's also ok

2022-07-09 18:44 UTC, marina-tilniak approved these changes

2024-12-11 13:30 UTC, closed without merging