solution
mate-academy/react_person pull request #62
Opened 2021-10-02 15:14 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/react_person/)

2021-10-04 18:24 UTC, varseniuk requested changes

2021-10-04 18:24 UTC, varseniuk commented on src/App.js
> +    />
```suggestion
    <Person person={ ...misha } />
```
Можна передавати цілий об'єкт і не розписувати кожне поле

2021-10-04 18:24 UTC, varseniuk commented on src/сomponents/Person/Person.jsx
> +  age: false,
```suggestion
  age: null,
```
age - це в нас number. Не варто давати йому булеве значення по дефолту

2021-10-09 08:42 UTC, Dinexpod commented on src/сomponents/Person/Person.jsx
> +  age: false,
зрозумів

2021-10-11 11:17 UTC, vkryvytskyi requested changes

2021-10-11 11:17 UTC, vkryvytskyy commented on src/App.js
> +    <Person person={alex} />
```suggestion
    <Person {...misha} />
    <Person {...olya} />
    <Person {...alex} />
```
Передавай объект в таком виде, тогда можно будет избавиться от лишней деструктуризации в компоненте

2021-10-11 11:17 UTC, vkryvytskyy commented on src/сomponents/Person/Person.jsx
> +  const { name, age, partnerName } = person;
```suggestion
export const Person = ({ name, age, partnerName }) => {
```

2021-10-16 18:47 UTC, Dinexpod commented on src/App.js
> +    <Person person={alex} />
аааааа, отак зрозумів))

2021-10-16 18:54 UTC, Dinexpod commented on src/сomponents/Person/Person.jsx
> +  const { name, age, partnerName } = person;
да да, тут вже зрозуміло по пораді вище як правильно передавати)

2021-10-16 18:56 UTC, Dinexpod commented
а можете будьласка проревьювити ще оці таски бо тоді коли щось упало в мейті то не назначався ревьювер і ви тепер його не перевіряєте. Це задачі з цієї теми

1) https://github.com/mate-academy/react_article/pull/509
2) https://github.com/mate-academy/react_sum/pull/509

2021-10-18 09:02 UTC, danylo-onishchuk approved these changes

2026-05-10 22:08 UTC, closed without merging