Solution
mate-academy/react_person pull request #720
Opened 2022-10-12 06:44 UTC by Yuriy-Komolov

[DEMO LINK](https://Yuriy-Komolov.github.io/react_person/)

2022-10-12 12:11 UTC, Oleksandra-Shevchenko approved these changes
LGTM 🥇

2022-10-13 08:27 UTC, Andr1yK requested changes

2022-10-13 08:27 UTC, Andr1yK commented on src/components/Person/Person.jsx
> +    <>
useless

2022-10-13 08:27 UTC, Andr1yK commented on src/components/Person/Person.jsx
> +          : null
use && operator

2022-10-13 08:27 UTC, Andr1yK commented on src/components/Person/Person.jsx
> +          )}
```suggestion
          {isMarried
            ? `${partnerName} is my ${partner}`
            :  'I am not married'
          }
```

2022-10-13 08:59 UTC, closed without merging