complete the task
mate-academy/react_person pull request #737
Opened 2022-10-14 16:41 UTC by barsuchellos

[DEMO LINK](https://barsuchellos.github.io/react_person/)

https://prnt.sc/Wdp-E8BT-bUe

2022-10-16 23:17 UTC, xiimiik requested changes
GJ, but need some fix

2022-10-16 23:17 UTC, xiimiik commented on src/components/Person/Person.jsx
> +            </p>
paragraph and class dont change, so change only the filling

2022-10-17 16:47 UTC, xiimiik approved these changes
Nice!

2022-10-17 17:53 UTC, Anna-Tkachenko requested changes

2022-10-17 17:53 UTC, Anna-Tkachenko commented on src/components/Person/Person.jsx
> +      )}
fix indents
```suggestion
      {age && (
        <p className="Person__age">
          {`I am ${age}`}
        </p>
      )}
```

2022-10-17 17:53 UTC, Anna-Tkachenko commented on src/components/Person/Person.jsx
> +        {!isMarried ? 'I am not married' : `${partnerName} is my ${partner}`}
```suggestion
        {!isMarried
          ? 'I am not married'
          : `${partnerName} is my ${partner}`}
```

2022-10-18 20:25 UTC, Anna-Tkachenko approved these changes

2024-10-18 08:51 UTC, closed without merging