Have some issues with npm
mate-academy/react_person pull request #921
Opened 2022-12-27 12:46 UTC by JzSol

2022-12-27 14:54 UTC, Lun4trick requested changes
Just need one little change, good work btw. 👍

2022-12-27 14:54 UTC, Lun4trick commented on src/components/Person/Person.jsx
> +    {person.age ? (
u should destructure person, and then use only the propertys instead of person.property, check the checklist for some instructions.

2022-12-28 22:50 UTC, Lun4trick approved these changes
GG 👍

2022-12-29 15:25 UTC, naziamoff approved these changes
🔥

2026-05-16 06:32 UTC, closed without merging