solution
mate-academy/react_person pull request #99
Opened 2021-10-09 13:48 UTC by Tarasulko

[DEMO LINK](https://tarasulko.github.io/react_person/)

2021-10-11 16:56 UTC, Anna-Tkachenko requested changes

2021-10-11 16:56 UTC, Anna-Tkachenko commented on src/components/Person.jsx
> +    return (
Для чего нужна эта проверка? Name - обязательное свойство, значит оно всегда будет

2021-10-11 16:56 UTC, Anna-Tkachenko commented on src/components/Person.jsx
> +        <p className="Person__age">{age && `I am ${age}`}</p>
Вынеси проверку age && за пределы параграфа p
Если age нет - параграф не отображается

2021-10-11 16:56 UTC, Anna-Tkachenko commented on src/components/Person.jsx
> +};
Добавь defaultProps для необязательных свойств (age и partnerName)

2021-10-25 03:48 UTC, mgrinko approved these changes

2024-10-22 13:50 UTC, closed without merging